version: "3.1"

services: 
  db: 
    image: postgres
    ports: 
      - "7777:5432"
    environment: 
      POSTGRES_USER: ubuntu  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: orb
    volumes:
      - orb:/var/lib/postgresql

volumes: 
  orb:
    external: false
